# Generated by Django 3.2 on 2024-11-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(max_length=250)),
                ('agency', models.CharField(max_length=100)),
                ('certifications', models.CharField(blank=True, max_length=200, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='agent_profiles/')),
                ('pan_card', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('aadhaar_card', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('aadhar', models.CharField(max_length=12, unique=True)),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('insurance_type', models.CharField(choices=[('Health', 'Health Insurance'), ('Life', 'Life Insurance'), ('Vehicle', 'Vehicle Insurance'), ('Home', 'Home Insurance')], max_length=20)),
                ('policy_number', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaign_banners/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='app.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app.agent')),
            ],
        ),
    ]
