# Generated by Django 3.2 on 2024-11-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_agent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agent'),
        ),
    ]
