# Generated by Django 3.2 on 2024-11-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_attendance_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.agent'),
        ),
    ]
