# Generated by Django 3.2 on 2024-12-05 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
