# Generated by Django 3.2 on 2024-12-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
