# Generated by Django 3.2 on 2024-12-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/d.webp', null=True, upload_to='agent_profiles/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, default='images/d.webp', null=True, upload_to='client_photos/'),
        ),
    ]
