# Generated by Django 3.2 on 2024-12-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20241205_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/2.png', null=True, upload_to='agent_profiles/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, default='images/2.png', null=True, upload_to='client_photos/'),
        ),
    ]
