# Generated by Django 3.2 on 2024-12-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20241205_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent',
        ),
    ]
