# Generated by Django 3.2 on 2024-12-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_agent_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
