# Generated by Django 3.2 on 2024-12-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_client_is_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='agent_profiles/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='client_photos/'),
        ),
    ]
