# Generated by Django 3.2 on 2024-12-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20241206_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='mobile_number',
        ),
    ]
