# Generated by Django 3.2 on 2024-12-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='end_date',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(default='DEFAULT_POLICY_NUMBER', max_length=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='policy',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='insurance_type',
            field=models.CharField(choices=[('Health', 'Health Insurance'), ('Life', 'Life Insurance'), ('Vehicle', 'Vehicle Insurance'), ('Home', 'Home Insurance')], max_length=20),
        ),
    ]
