# Generated by Django 3.2 on 2024-12-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20241221_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='description',
        ),
    ]
