# Generated by Django 3.2 on 2024-12-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_policy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
