# Generated by Django 3.2 on 2024-12-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_policy_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
