# Generated by Django 3.2 on 2024-12-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='certifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='languages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='specialization',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
