# Generated by Django 3.2 on 2024-12-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20241226_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='certifications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
